version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    build: .
    command: bash -i -c 'rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
