version: '2'
services:
  app:
    build: .
    command: bash -i -c 'rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file: .env